import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./animate.min.css";
import "./slick.css";
import "./tailwind-built.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Container from "@/components/container";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "(temp) Dalongo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <Container>
          <Header />
          {children}
        </Container>
        <Footer />
      </body>
    </html>
  );
}
